### PR TITLE
Adding channel and data types management, properties edition and cont…

### PR DESCRIPTION
**Pull request by lbroudoux**
…ext-menus on AsyncAPI editor

As discussed into #447, this is a second PR to pursue the AsyncAPI graphical editor into Apicurio!

This second PR embeds following changes and capabilities:
* Graphical `Channel` creation / deletion as well as support for context-menu,
* Support of `SchemaDefinition` management: creation, cloning and deletion,
* Schema properties graphical edition.

Some screenshots below:
Capture d’écran 2020-09-24 à 14 12 51
Capture d’écran 2020-09-24 à 14 13 05
Capture d’écran 2020-09-24 à 14 13 31

### CODE REVIEW

**Comment by EricWittmann** [comment]
Very nice, thanks.  We'll need to do a release of data-models before this PR will pass.

**Comment by lbroudoux** [comment]
Great! Meanwhile I'll do some changes to activate the "Mock with Microcks" button for AsyncAPI too.

**Comment by EricWittmann** [comment]
Release is done:  https://github.com/Apicurio/apicurio-data-models/releases/tag/1.1.5

You should be able to update both the `pom.xml` and `package.json` with the new version and the CI build should then hopefully work.

**Comment by lbroudoux** [comment]
Hey @EricWittmann ,

Just changing the `pom.xml` and `package.json` is not enough as you have made some other refactoring ;-)

The moves of `Aai20SchemaDefinition` to `AaiSchema` are causing some blocking issues. For instance, because `AaiComponents` having a `Map<String, AaiSchema> schemas`, we studio can no longer retrieve a data type definition by name, the `name` property still being hold by `Aai20SchemaDefinition` ...

To be analog to what we're having on OpenAPI, I think we should introduce an `AaiSchemaDefinition`, make use of this one in `AaComponents` and having the concrete `Aai20SchemaDefinition` inherit this new class.

**Comment by EricWittmann** [comment]
OK sorry for that.  The schemas in components should all actually be `Aai20SchemaDefinition` instances, though.  Can you not just cast them?

**Comment by lbroudoux** [comment]
Oh well yes of course, it should work ... but I was wondering why we would not reproduce same design than in `OAS30Components` ?

**Comment by lbroudoux** [comment]
Hooray ! Build is OK ;-)

**Pull request merged**
