### PR TITLE
adding the UI for Oas3Types : title,minimum,maximum,maxLength,minLeng…

### PR DESCRIPTION
**Pull request by vvilerio**
Hi, the next part as promised.

adding the UI for Oas3Types : title, minimum, maximum, maxLength, minLength, exclusiveMaximum, exclusiveMinimum,
pattern, maxItems, minItems, uniqueItems, multipleOf, minProperties and maxProperties

see: https://github.com/Apicurio/apicurio-studio/issues/1193

### CODE REVIEW

**Comment by vvilerio** [comment]
minPropertiesButtonsWithRed
minPropertiesButtons

**Comment by EricWittmann** [comment]
Thanks @vvilerio !  I'm going on PTO for the next two weeks, so there will be a bit of a delay on anything Studio until I'm back. :)

**Comment by vvilerio** [comment]
Hi ! @EricWittmann 
are you back ?

**Comment by EricWittmann** [comment]
Yes - sorry for the delay.  I've started looking at this multiple times only to be derailed either by bugs or higher priority (i.e. actively on-fire) tasks.

I haven't forgotten! :)

**Comment by EricWittmann** [comment]
Looking at this (finally) now.  I dont' see the - and + buttons you highlighted in the first screenshot.  I see the new min/max etc config in the property type editor... but I don't see the Min/Max Properties action.  Am I looking in the wrong place?

As for the UI of the other properties.  I'll probably tweak the UX a little bit, but this looks like a solid start.

**Comment by vvilerio** [comment]
For to see the - and + buttons you have to switch from simple type  into "complex Object"

**Comment by EricWittmann** [comment]
Hm... OK I'll try again later today.

**Comment by EricWittmann** [comment]
Making slow progress on this - other things are getting in the way, but I'll get this merged soon, really!

**Comment by EricWittmann** [comment]
BTW that did the trick - switching to complex Object.  Thought it already was, because I was editing properties.  Perhaps a bug...

**Comment by EricWittmann** [comment]
OK @vvilerio I know it's been like a million years on this.  I finally finished going through this PR.  I made some changes on the look and feel to bring it more inline with the existing UX.  Here are some screenshots of what it looks like now:

**Min/Max Properties**
image

**Property Extra Config**
image

Thank you for the contribution!  This is a really nice improvement.

@lbroudoux is this something that should be included in the AsyncAPI editor do you think?

**Comment by vvilerio** [comment]
Good news, and very nice tricks in the UX @EricWittmann

**Pull request merged**
