### PR TITLE
chore: bump apicurio-data-models to 1.1.24

### PR DESCRIPTION
**Pull request by craicoverflow**

### CODE REVIEW

**Comment by craicoverflow** [comment]
I've closed this to see whether dependabot will pick up the new version

**Comment by EricWittmann** [comment]
I'm working through some issues with Studio, codegen, and data-models.  So probably best not to merge a data-models PR from renovate even if it recreates it.

**Comment by craicoverflow** [comment]
Sure.

**Comment by EricWittmann** [comment]
We're all good now.  I've released data-models and codegen both.  And I've upgraded both of those in studio.  So everything now works including the Studio build (I hope).

**Pull request closed without merging**
