### PR TITLE
Sample i18n (Japanese)

### PR DESCRIPTION
**Pull request by turutosiya**
Hi @EricWittmann ,

[Based on your suggestion](https://github.com/Apicurio/apicurio-studio/issues/22#issuecomment-756958467), I just imeplemted i18n feature for studio and create a very simple & small PR to evaluate the way to implement i18n.

In this PR, only the labels in the side menu are localized:

Screen Shot 2021-01-27 at 16 37 05

You can test this by running studio with `--configuration=ja` option.

```
$ ng serve --port 8888 --aot --configuration=ja
```

### CODE REVIEW

**Comment by msavy** [comment]
I'm impressed, this seems quite unobtrusive!

**Comment by EricWittmann** [comment]
This looks good to me!  And I agree is very unobtrusive.

Some questions I have after seeing this:

* This requires a separate build of the UI for each locale, correct?  If so, are they all bundled and released together so that the locale can be selected at runtime?  Or is a separate binary release of Studio needed for each locale?
* It looks good for simple labels, how does it work for more complex strings that perhaps have dynamic information injected?
* Does the i18n support also work with attributes?  (for example the `title` attribute)

**Comment by turutosiya** [comment]
> * This requires a separate build of the UI for each locale, correct?  If so, are they all bundled and released together so that the locale can be selected at runtime?  Or is a separate binary release of Studio needed for each locale?

In this case, I tried with AOT compile option. So, it requires a separate build of the UI for each locale.
And I think we can bundle all of the locales together by adjusting `outputPath` of `angular.json`.
( Switch `outputPath` for each locales.  )

Besides, there is a `JIT` option.
With that option, we can switch language at runtime.
But, it will impact current code base and also the performance. 

> * It looks good for simple labels, how does it work for more complex strings that perhaps have dynamic information injected?

Let me try.

> * Does the i18n support also work with attributes?  (for example the `title` attribute)

Yes, of course. For attribute, we can do this way:

```
<img [src]="logo" i18n-title title="i18ned title" />
```

Also, we can translate without any tag :

```
<ng-container i18n>I don't output any element</ng-container>
```

**Comment by EricWittmann** [comment]
OK thanks for answering my questions.  I think this looks fantastic!  I would be very happy to have this contribution.

**Comment by EricWittmann** [comment]
If you want, we can create a separate i18n branch and merge it all in at once later, or you can continue updating this PR.   How do you want to proceed?

**Comment by turutosiya** [comment]
@EricWittmann 
> If you want, we can create a separate i18n branch and merge it all in at once later
That sound good to me.

**Comment by turutosiya** [comment]
@EricWittmann Please let me know when you have done creating i18n branch?

**Comment by EricWittmann** [comment]
Whoops!  Sorry for the delay on this:

https://github.com/Apicurio/apicurio-studio/tree/feat/i18n

Feel free to open up PRs against that branch in whatever granularity suits you.

**Pull request closed without merging**
