### PR TITLE
Configured WS pod to be exposed via Ingress

### PR DESCRIPTION
**Pull request by cemnura**
Signed-off-by: Cem Nura <cem.nura@gmail.com>

### CODE REVIEW

**Comment by cemnura** [comment]
Kubernetes Ingress Websocket problem.

Fixes: 1171

**Comment by EricWittmann** [comment]
Thanks @cemnura !  Hey @jsenko can you have a look at this and let me know what you think?

**Comment by cemnura** [comment]
Hello @EricWittmann I thought this PR was going to be superseded by the recent developments discussed on issue #1171

**Comment by EricWittmann** [comment]
Yes you are right, @cemnura sorry about that.  My mistake.  I can revert the change if you would like or we can push forward.  Thoughts?

**Comment by EricWittmann** [comment]
Also @t-rap your thoughts?

Oh, and don't forget about this work:  https://github.com/Apicurio/apicurio-studio/tree/master/distro/helm

I'm not sure whether that is perhaps even more interesting for you?

**Comment by t-rap** [comment]
@EricWittmann my job is eating me right now. i'll think this through on the weekend, if that is okay for you.

thanks for the link by the way. I disliked helm in the past, but i'll have a look, as it is officially state of the art ^^

**Comment by EricWittmann** [comment]
Great thanks - for the record, the long term solution to installing on Kubernetes will absolutely be a Go based k8s operator available on operator hub.  However, the timeline for that work is unknown right now and will depend a lot on priorities here at Red Hat.  But I do anticipate that to happen hopefully in 2020.  

Assuming we aren't all conquered by hypno-toads or something (likely given 2020's trajectory). :)

**Comment by cemnura** [comment]
Hi @EricWittmann, I belive @t-rap ingress configuration would be a much preferred option. Therefore, I thought @t-rap  could provide the kubernetes ingress configuration with my observations that I have stated on the issue #1171

A helm configuration would be greatly helpful indeed. I see it has been added recently. Will there be an addition to the stable helm repository?

**Pull request merged**
