### PR TITLE
#700 added docker-compose distro without reverse proxy and SSL support

### PR DESCRIPTION
**Pull request by chriske**

### CODE REVIEW

**Comment by chriske** [comment]
#700

**Comment by EricWittmann** [comment]
Taking a look at this now, sorry for the delay.

**Comment by EricWittmann** [comment]
This is a fantastic start - I tried it and it worked great.  There are some improvements I think we can/should make and I'm not 100% sure how to address them all.  So here is some feedback and we can discuss (in no particular order):

1) I can't log in to Microcks and there is no **Register User** option
2) The Apicurio version is hard-coded and should either be parameterized in some way or else set to "latest-release" and then modified to a specific version whenever a release is done (similarly to what is done now for the OpenShift templates)
3) Missing the Keycloak login theme for Apicurio (i.e. getting the classic Keycloak theme rather than the Apicurio theme for the login page)
4) Logout is broken (the logout servlet is redirecting to `/studio` and should be configured)

**Comment by EricWittmann** [comment]
The issue with (1) is just realm configuration - so we can update the microcks realm file to enable registration.

**Comment by EricWittmann** [comment]
For (4) we need to introduce the following environment variable:

`APICURIO_UI_LOGOUT_REDIRECT_URI`

And its value should be:

`/`

**Comment by EricWittmann** [comment]
I guess for (3) we would need a custom image to install the theme.  For reference the Apicurio KC login theme is here:

https://github.com/Apicurio/apicurio-studio/tree/master/distro/keycloak/themes-kc3/apicurio

**Comment by EricWittmann** [comment]
So @chriske - thoughts on the other items in the list?  I'm actually happy accepting this PR as-is and we can address some of these issues iteratively if you'd prefer.

**Comment by chriske** [comment]
@EricWittmann Thank you for your feedback! I totally agree with your improvements. I think I'm going to extend this PR with (1)-(4). I also want to extend the Readme with some configuration part and explanation.

(5) and (6) are a little bit more complex, but we can do them later, it's not an issue.  To make (5) possible, I will introduce a new compose and .env file. For (6) I think I have a really nice solution, and we can extend the setup procedure with password generation too (and we should also generate the api key for microcks too).  This can be the 2nd iteration of the task, and the last one will be the reverse proxy and SSL support.

**Comment by chriske** [comment]
I finished the modifications:

(1) - modified Microcks realm config, users can now register directly
(2) - made the versions configurable in the .env file, the default docker tag is: `latest-release`. Also added a new section about this into the Readme
(3) - added a build step, which will create an own keycloak image based on the context of the compose file. This means I had to extend the starting steps in the Readme. I created a keycloak folder in the docker-compose folder, and that folder contains the new Dockerfile and your theme. Unfortunately I can't link it to the already existing folder in dist, because it has to be inside the docker-compose folder :(
(4) - added the new ENV variable with your default value

If you tried it, and you think it's good enough, merge it please. We will do the next steps with new issues/PRs if that's OK for you.

Thanks!

**Comment by EricWittmann** [comment]
Thanks for doing those updates, @chriske - I'm hopeful I will be able to re-test this today or tomorrow and then get it merged.

**Comment by EricWittmann** [comment]
Hey @chriske this is all really great.  All my testing was successful.  I look forward to future improvements!  But what an amazing start, and it's such a great way for docker users to get going quickly.  I'm going to update the project website to include instructions for running this way (probably just link to your readme).

**Comment by chriske** [comment]
Hey @EricWittmann thanks for your kind words! You're welcome!

**Pull request merged**
