### PR TITLE
Adding support for Operation/Message/Examples edit

### PR DESCRIPTION
**Pull request by lbroudoux**
Here are some enhancements for the Studio. See capture below:

Capture d’écran 2021-01-21 à 12 29 41

### CODE REVIEW

**Comment by EricWittmann** [comment]
Nice!  The data-models release failed when trying to publish to maven central. :(  I'm looking into it.

**Comment by EricWittmann** [comment]
All fixed.  The 1.1.7 release of data models should now be available.

**Comment by EricWittmann** [comment]
Can you rebase this to `master` so that CI runs again?

**Comment by lbroudoux** [comment]
In progress ;-)

**Comment by lbroudoux** [comment]
Ouch .... `1.1.7` release it still missing in https://repo.maven.apache.org/maven2/io/apicurio/apicurio-data-models/...

**Comment by EricWittmann** [comment]
@lbroudoux The latest build failure:  https://gist.github.com/EricWittmann/68e821fe4ec018c203e01947bfc74070

**Comment by lbroudoux** [comment]
Tadam! Finally fix latest typescript prod compilation issue!

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
