### PR TITLE
Prepare i18n

### PR DESCRIPTION
**Pull request by turutosiya**

### CODE REVIEW

**Comment by turutosiya** [comment]
@EricWittmann I rebased master & resolved some conflicts. would you please check?

**Comment by carlesarnal** [comment]
Hi @turutosiya,

when I try to run the application I'm getting an error in the UI, `$localize is not defined` any idea about what might be happening?

**Comment by turutosiya** [comment]
@carlesarnal Thanks for your reporting. Let me check that error.

**Comment by carlesarnal** [comment]
@turutosiya this PR has been open for a while, any updates?

**Pull request closed without merging**
