### PR TITLE
Distributed session support and integration testing, with Artemis implementation

### PR DESCRIPTION
**Pull request by msavy**
Working PR as discussed.

p.s. apologies for the ridiculous history, but haven't had time to squash, etc.

### CODE REVIEW

**Comment by EricWittmann** [comment]
CircleCI build fails for this PR.  I may just merge it onto the `jms` branch and then fix it... we'll see. :)  Got some other things to take care of first.

**Comment by msavy** [comment]
Maybe I missed something out of the push. Will check when I get home. Will
be a couple of hours.

**Comment by EricWittmann** [comment]
Might be a dependency loop between the modules.  I haven't looked yet.

**Comment by EricWittmann** [comment]
Thanks!  I'm going to start having a look at this next week.

**Pull request merged**
