### PR TITLE
init helm installation

### PR DESCRIPTION
**Pull request by tomassatka**
Hi team 

I wrote initial helm 3 installation. I was able to test it locally only by rendering 

> helm template apicurio .

Had some issues to pull remote images to my minikube cluster therefore kindly asking if you can try this installation to any of your k8s clusters. My intention is to build upon this and apply to openshift 3.11 as we do for any other helm k8s installation. Happy to get feedback

### CODE REVIEW

**Comment by jbadeau** [comment]
awesome

**Comment by EricWittmann** [comment]
I don't have a ready way to test this right now.  I'll see what I can do to find someone who can test it...

**Comment by tomassatka** [comment]
Hi team

I made local testing and looked fine. But please go ahead and confirm also on your side that the installation works as expected. 
My setup:

minikube

keycloak installed from helm helm -> https://hub.helm.sh/charts/codecentric/keycloak

added ingress for keycloak :
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: keycloak-http
  annotations:
  labels:
    app.kubernetes.io/instance: keycloak
spec:
  rules:
  - host: keycloak-http
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: 80
        path: /
```
modified /etc/hosts to add 
```
$minikubeIP: apicurio
$minikubeIP: keycloak-http
```

**Comment by EricWittmann** [comment]
I don't want to hold up this PR waiting for me to find time to test it locally.  I will still do that when I have time - but I'm going to be away from work for a while and don't want this sitting around for no reason. :)  Thanks for the contribution @tomassatka !

**Pull request merged**
