### PR TITLE
Asyncapi features: servers, security schemes and misc fixes

### PR DESCRIPTION
**Pull request by DyspC**
Hello, 

This PR makes the servers, security schemes and security requirements editable on asyncapi specifications.

I squashed a bit roughly but there are some other misc changes:
- `front-end/studio/src/app/components/common/activity-item.component.ts` Many commands were not described there so I added a bunch (not sure if I added both icons and descriptions everywhere)
- `front-end/studio/src/app/pages/apis/{apiId}/editor/_components/aaimaster.component.ts` A little comment about the getCurrentChannelSelection function that probably does not belong there
- `front-end/studio/src/app/pages/apis/{apiId}/editor/aaieditor.component.ts` I added the ApiCatalogService to fix the issue we discussed [there](https://github.com/Apicurio/apicurio-studio/pull/1381#issuecomment-853999493)
- `front-end/studio/src/app/pages/apis/{apiId}/editor/_components/aaimaster.component.ts` I added the delete implementations but atm the deleteDefinition does nothing. This should be fixed later with a data-models publication

### CODE REVIEW

**Comment by EricWittmann** [comment]
If I do a release of apicurio-data-models would you want to update this PR before merging?

**Comment by DyspC** [comment]
I can do the update

**Comment by EricWittmann** [comment]
OK great!  Version 1.1.12 of data models is released.  :)

**Review by EricWittmann — APPROVED** [review]
Awesome contribution, thank you!

**Comment by EricWittmann** [comment]
@DyspC and @lbroudoux - with this update should we enable AsyncAPI by default in Studio?

**Comment by DyspC** [comment]
> @\DyspC and @\lbroudoux - with this update should we enable AsyncAPI by default in Studio?

We got 2 feedbacks from our testers:
- Collaboration is disabled. (I did not dig into this to know what isn't ready there)
- The "Live Documentation" button from inside the api editor is active as opposed to "Preview Documentation" in the api page (I think since the live documentation expects an openapi document we should add an if(oas2 || oas3) there as well)

---
https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/%7BapiId%7D/api-detail.page.ts#L271

**Comment by EricWittmann** [comment]
OK great - can you open a couple of GH issues so we can take care of those things?

**Comment by DyspC** [comment]
I've dug a bit and am gonna write a PR tomorrow for those two since it looked OK (#1568 #1569) (and perhaps the yarn proxy configuration as well who knows ;))

**Comment by lbroudoux** [comment]
Hi @EricWittmann and @DyspC,

I don't think we can made AsyncAPI enable by default because as of AsyncAPI 2.1.0 release (it was yesterday) the format of message examples has evolved to become more formal. Good news for Microcks ;-) but I think we should report this evolution to Apicurio before making it GA.

I plan to spend some hours on that next week with also the bindings support. Keep you updated very soon.

**Comment by EricWittmann** [comment]
OK that's great, thanks for the update.

**Comment by lbroudoux** [comment]
Just pushed the change and make a PR here: https://github.com/Apicurio/apicurio-studio/pull/1574

**Pull request merged**
