### PR TITLE
adding maximum, minimum, maxLength,minlength, pattern oas3 types

### PR DESCRIPTION
**Pull request by vvilerio**
Hello,

this PR adding maximum, minimum, maxLength, minlength, pattern ( OAS 3 imported types from JSON Schema )

The next part is coming soon.

See : https://github.com/Apicurio/apicurio-studio/issues/1193

Have a good day.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Can you add a screenshot of what this change looks like?

**Comment by vvilerio** [comment]
Yes :)
[image](http://transfer.sh/1gb5r1D/minmax.png)

**Comment by EricWittmann** [comment]
Looks good thanks!  I think there may be some UI tweaking we could do on this, but it's a great start. :)

**Comment by vvilerio** [comment]
Good, I agree (  the all inline is not optimum ), I was thinking to tweak the css afterwards to have a more armonious rendering .
Next soon.

**Pull request merged**
