### PR TITLE
[i18n] Japanese Language localization

### PR DESCRIPTION
**Pull request by turutosiya**
- rebased 0.2.48.Final
- Add basic configuration for Japanese UI
- localized: dashboard page, API list page, API creation page

### CODE REVIEW

**Comment by turutosiya** [comment]
@EricWittmann Would you kindly please review & merge this PR?
- Rebased 0.2.48.Final
- Add basic configuration for Japanese UI
- Localized: dashboard page, API list page, API creation page

**Comment by EricWittmann** [comment]
Thanks @turutosiya !  I have actually rebased the `feat/i18n` branch to master and then cherry-picked your commit and pushed that up.  I'm closing this PR as a result, since github wasn't smart enough to figure out what I did. :)  Sorry about that.

Question:  I'm noticing that the messages file contains source file and line number information.  Does that represent a maintenance challenge?   What happens to the translation process when a source file is modified (e.g. due to implementing a new feature)?

**Comment by turutosiya** [comment]
@EricWittmann Thanks! I recognized that the commit was cherry-picked.

By the way, what do you mean by `maintenance challenge`?

**Comment by EricWittmann** [comment]
Well, if the translation files reference a specific file and line number in that file, does the translation break when the original file is changed in a way that modifies the line numbers?  If yes, that will make it hard to maintain the translation files when new features are added to the UI (which might cause existing HTML to be reformatted, removed, or simply shifted within a source file).

**Comment by turutosiya** [comment]
> Well, if the translation files reference a specific file and line number in that file, does the translation break when the original file is changed in a way that modifies the line numbers? If yes, that will make it hard to maintain the translation files when new features are added to the UI (which might cause existing HTML to be reformatted, removed, or simply shifted within a source file).

Thanks. I understood and I agree. We removed `context` tags from language resource files and checked. it works!
I created a new PR:

https://github.com/Apicurio/apicurio-studio/pull/1487

Please check.

**Pull request closed without merging**
