### PR TITLE
CORS config for UI

### PR DESCRIPTION
**Pull request by romilin**
Hello @EricWittmann ,

The recent modification about CORS seems to be missing something. 
I have just copy what you write in the API config and add it to the UI config. 

It solves this problem for me : 
image

### CODE REVIEW

**Review by v-bilous — APPROVED** [review]

**Review by v-bilous — APPROVED** [review]

**Comment by v-bilous** [comment]
Hello, this PR will fix the issue https://github.com/Apicurio/apicurio-studio/issues/2130

**Comment by crmccar** [comment]
I believe this issue is completing blocking use of https://studio.apicur.io/. I could be wrong, but I'm stuck on the loading image and the CORS errors are the only thing showing up in the Chrome web development console.

**Comment by EricWittmann** [comment]
See my comment on https://github.com/Apicurio/apicurio-studio/issues/2130 - I don't **think** this is needed.  But please correct me if I'm wrong and provide a configuration that's failing for you.  :)

**Comment by EricWittmann** [comment]
Although I see from your screenshot that maybe you're getting CORS failures trying to load certain resources.

**Comment by andapony** [comment]
I'm getting the same problem, both with Chrome and Safari.

**Comment by EricWittmann** [comment]
You're right - I was using Firefox.  Chrome fails for me.

I'll merge this PR and fix the issue on studio.apicur.io (which doesn't require a new release).

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
